openapi: "3.0.3"

info:
  version: "1.0"
  title: Self-Assessment Test Support (MTD)
  description: |
    # Changelog
    The changelog is [available here](https://github.com/hmrc/income-tax-mtd-changelog/#readme).
    
    # Support
    
    * Raise non-technical or platform-related issues with the [Software Development Support Team (SDST)](https://developer.service.hmrc.gov.uk/developer/support).
    * Raise technical issues on the [income-tax-mtd-changelog](https://github.com/hmrc/income-tax-mtd-changelog/issues) GitHub page.
    * [Is this page not working properly?](https://developer.service.hmrc.gov.uk/contact/report-technical-problem?newTab=true&service=api-documentation-frontend)

servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox

components:
  securitySchemes:
    Application-Restricted:
      type: oauth2
      description: |
        HMRC supports OAuth 2.0 for authenticating [Application-Restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints) API requests using an OAuth 2.0 Bearer Token.
      flows:
        clientCredentials:
          tokenUrl: https://api.service.hmrc.gov.uk/oauth/token
          scopes:
            write:self-assessment: Grant write access
            read:self-assessment: Grant read access

paths:
  /individuals/self-assessment-test-support/vendor-state:
    $ref: "./vendor_state.yaml"
  # {{#if (enabled "checkpointing")}}
  /individuals/self-assessment-test-support/vendor-state/checkpoints:
    $ref: "./checkpoints_1.yaml"
  /individuals/self-assessment-test-support/vendor-state/checkpoints/{checkpointId}:
    $ref: "./checkpoints_delete.yaml"
  /individuals/self-assessment-test-support/vendor-state/checkpoints/{checkpointId}/restore:
    $ref: "./checkpoints_restore.yaml"
  # {{/if}}
  /individuals/self-assessment-test-support/business/{nino}:
    $ref: "./business_create.yaml"
  /individuals/self-assessment-test-support/business/{nino}/{businessId}:
    $ref: "./business_delete.yaml"
  # {{#if (enabled "create-amend-itsa-status")}}
  /individuals/self-assessment-test-support/itsa-status/{nino}/{taxYear}:
    $ref: "./itsa_status_create_amend.yaml"
  # {{/if}}

